# Use root/example as user/password credentials
version: '3.1'
services:
  mongo:
    image: mongo:4.0
    restart: always
    hostname: xxsoar_mongo
    volumes:
     - /var/log/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: xsoar
      MONGO_INITDB_ROOT_PASSWORD: xsoaristhebestidea

  redis:
    image: "redis"
    restart: always
    hostname: xxsoar_redis
    command: redis-server --requirepass "xsoaristhebestidea"
    ports:
      - "6379:6379"

  nuclio:
    image: "xxwsy/nuclio"
    restart: always
    hostname: xxsoar_nuclio
    ports:
      - "8070:8070"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

  backend:
    image: "xxwsy/xxsoar:latest"
    restart: always
    hostname: xxsoar
    ports:
      - "8000:8000"
    command:
     - sh
     - -c
     - | 
       supervisord -c /app/supervisord.conf


