# Use root/example as user/password credentials
version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
     - /var/log/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: xsoar
      MONGO_INITDB_ROOT_PASSWORD: xsoaristhebestidea

  redis:
    image: "redis"
    restart: always
    hostname: web_redis
    command: redis-server --requirepass "xsoaristhebestidea"
    ports:
      - "6379:6379"

  backend:
    image: "xxwsy/xxsoar"
    restart: always
    network_mode: host
    command:
     - sh
     - -c
     - | 
       supervisord -c /app/supervisord.conf


